import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
// import "bootstrap/dist/css/bootstrap.min.css"; // Import bootstrap CSS
// import "./globals.css";

import "../styles/main.scss";
import LoginPage from "./(public)/login/page";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = (await cookies()).get("token")?.value;
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {token ? <Providers>{children}</Providers> : <LoginPage />}
      </body>
    </html>
  );
}
